#!/bin/bash -eu
set -o pipefail

DOCKER_IMAGE=kata-rnc/build-c

if [[ $DOCKER_IMAGE != ${DOCKER_CONTAINER-} ]]; then
    source_dir="$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")"

    echo -n "Base Docker: "
    docker build ${DOCKER_QUIET-} \
           --force-rm --rm=true \
           -t "$DOCKER_IMAGE" \
           "$source_dir/do/c.docker"

    "$source_dir/do/create-user" "$DOCKER_IMAGE"

    output_dir="${source_dir}/acceptance-test/rust"
    if [[ -e "$output_dir" ]]; then
        echo rm -rf "$output_dir"
        rm -rf "$output_dir"
    fi
    mkdir -p "$output_dir"

    tty=
    if [[ -t 1 ]]; then
        tty=-t
    fi
    docker run $tty \
           --env DOCKER_CONTAINER=$DOCKER_IMAGE \
           --env "source_dir=$source_dir" \
           --rm \
           --sig-proxy=true \
           --volume="$source_dir:$source_dir:ro" \
           --volume="$output_dir:$output_dir:rw" \
           --workdir="$source_dir" \
           $DOCKER_IMAGE-user \
           "$source_dir/do/acceptance-rust"
    exit $?
fi

if [[ -t 1 ]]; then
    if make -f Makefile.rust acceptance-test; then
        echo -e "\e[92;1m   A_A
 =(o.o)=    ,
 (  _  )--'
  !! !!      SUCCESS!\e[0m"
    else
        echo -e "\e[91;1m   A_A
 =(x.x)=    ,
 (  _  )--'
  !! !!      FAIL.\e[0m"
        exit 1
    fi
else
    make -f Makefile.rust acceptance-test
fi
