#!/bin/bash -eu
set -o pipefail

DOCKER_IMAGE=kata-rnc/analyze-c

if [[ $DOCKER_IMAGE != ${DOCKER_CONTAINER-} ]]; then
    source_dir="$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")"

    echo -n "Base Docker: "
    docker build ${DOCKER_QUIET-} \
           --force-rm --rm=true \
           -t "$DOCKER_IMAGE" \
           "$source_dir/do/c.docker"

    "$source_dir/do/create-user" "$DOCKER_IMAGE"

    output_dir="${source_dir}/analyze/c"
    if [[ -e "$output_dir" ]]; then
        echo rm -rf "$output_dir"
        rm -rf "$output_dir"
    fi
    mkdir -p "$output_dir"

    tty=
    if [[ -t 1 ]]; then
        tty=-t
    fi
    docker run $tty \
           --env DOCKER_CONTAINER=$DOCKER_IMAGE \
           --env "source_dir=$source_dir" \
           --env "output_dir=$output_dir" \
           --rm \
           --sig-proxy=true \
           --volume="$source_dir:$source_dir:ro" \
           --volume="$output_dir:$output_dir:rw" \
           --workdir="$source_dir" \
           $DOCKER_IMAGE-user \
           "$source_dir/do/analyze-c"
    exit $?
fi

analyze() {
    local errs=0

    if ! scan-build \
        -o "$output_dir/clang-check" \
        -enable-checker alpha.core.BoolAssignment \
        -enable-checker alpha.core.CastSize \
        -enable-checker alpha.core.CastToStruct \
        -enable-checker alpha.core.FixedAddr \
        -enable-checker alpha.core.IdenticalExpr \
        -enable-checker alpha.core.PointerArithm \
        -enable-checker alpha.core.PointerSub \
        -enable-checker alpha.core.SizeofPtr \
        -enable-checker alpha.cplusplus.NewDeleteLeaks \
        -enable-checker alpha.cplusplus.VirtualCall \
        -enable-checker alpha.deadcode.IdempotentOperations \
        -enable-checker alpha.deadcode.UnreachableCode \
        -enable-checker alpha.security.ArrayBoundV2 \
        -enable-checker alpha.security.MallocOverflow \
        -enable-checker alpha.security.ReturnPtrRange \
        -enable-checker alpha.security.taint.TaintPropagation \
        -enable-checker alpha.unix.Chroot \
        -enable-checker alpha.unix.MallocWithAnnotations \
        -enable-checker alpha.unix.PthreadLock \
        -enable-checker alpha.unix.SimpleStream \
        -enable-checker alpha.unix.Stream \
        -enable-checker alpha.unix.cstring.BufferOverlap \
        -enable-checker alpha.unix.cstring.NotNullTerminated \
        -enable-checker security.FloatLoopCounter \
        -enable-checker security.insecureAPI.rand \
        -enable-checker security.insecureAPI.strcpy \
        --status-bugs \
        make all LIBDIR="$output_dir/clang-check"
    then
        echo >&2 "clang-check FAILED"
        errs=$(( $errs + 1 ))
    fi

    local includes=("-I$source_dir/src/c")
    while read; do
        includes+=(-I$REPLY)
    done < <(echo | cpp -v 2>&1 | sed \
                -e '1,/#include <\.\.\.> search starts here:/d' \
                -e 's/^ //' \
                -e '/End of search list./,$d')

    if ! cppcheck \
        "${includes[@]}" \
        --enable=warning,style,warning \
        --error-exitcode=1 \
        --check-config \
        "$source_dir/src/c"
    then
        echo >&2 "cppcheck FAILED"
        errs=$(( $errs + 1 ))
    fi

    return $errs
}

if [[ -t 1 ]]; then
    if analyze; then
        echo -e "\e[92;1m   A_A
 =(o.o)=    ,
 (  _  )--'
  !! !!      SUCCESS!\e[0m"
    else
        echo -e "\e[91;1m   A_A
 =(x.x)=    ,
 (  _  )--'
  !! !!      FAIL.\e[0m"
        exit 1
    fi
else
    analyze
fi
